import type {
  AttentionRegion,
  ExplainabilityResult,
  LesionAnalysis,
  LesionClass,
  Point,
  StructureAnalysis,
} from '../types';
import { LESION_TAXONOMY } from '../constants';
import { quadrantOf } from '../../vision/anatomy';
import { boxBlur, type RasterImage, type RetinalMask } from '../../vision/raster';
import type { GradingReview } from '../../mistral/schemas';

const GRID = 16;
/** Alignment kernel width — roughly one disc diameter in normalised units. */
const SIGMA = 0.1;

/**
 * Stage 5 — why did the system decide this?
 *
 * Deliberately deterministic. Explainability that is itself generated by the
 * model being explained is not explanation, it is narration. Everything here is
 * computed: the attention field comes from the grading stage, the evidence map
 * comes from the detection stage, and the overlap score is a measurement of how
 * far apart those two things are.
 */
export function runExplainabilityStage(
  raster: RasterImage,
  field: RetinalMask,
  lesions: LesionAnalysis,
  structures: StructureAnalysis,
  attentionRegions: GradingReview['attentionRegions'],
  keyEvidence: string[],
  vesselMask: Uint8Array,
): ExplainabilityResult {
  const usingModelAttention = attentionRegions.length > 0;

  const grid = usingModelAttention
    ? gridFromRegions(attentionRegions)
    : gridFromImageEnergy(raster, field, vesselMask);

  normaliseGrid(grid);

  const lesionPoints = lesions.lesions.map((l) => l.centre);

  /* Strict mass decomposition: where does the attention actually land? */
  let total = 0;
  let onLesions = 0;
  let onAnatomy = 0;
  const discR = Math.max(0.05, structures.opticDisc.radius * 1.4);
  const macR = Math.max(0.09, structures.macula.radius);

  for (let r = 0; r < GRID; r++) {
    for (let c = 0; c < GRID; c++) {
      const w = grid[r][c];
      if (w <= 0) continue;
      total += w;
      const p = cellCentre(r, c);
      const nearLesion = lesionPoints.some(
        (l) => Math.hypot(l.x - p.x, l.y - p.y) <= 0.5 / GRID + 0.012,
      );
      if (nearLesion) {
        onLesions += w;
        continue;
      }
      const nearDisc =
        Math.hypot(p.x - structures.opticDisc.centre.x, p.y - structures.opticDisc.centre.y) <=
        discR;
      const nearMacula =
        Math.hypot(p.x - structures.macula.centre.x, p.y - structures.macula.centre.y) <= macR;
      if (nearDisc || nearMacula) onAnatomy += w;
    }
  }

  const attentionOnLesionsPct = total ? Math.round((onLesions / total) * 100) : 0;
  const attentionOnAnatomyPct = total ? Math.round((onAnatomy / total) * 100) : 0;
  const attentionUnexplainedPct = Math.max(
    0,
    100 - attentionOnLesionsPct - attentionOnAnatomyPct,
  );

  /* Soft alignment: how close is the attention mass to the nearest piece of
     evidence, tolerating the fact that attention is coarse and lesions are not. */
  const targets: Point[] = lesionPoints.length
    ? lesionPoints
    : [structures.macula.centre, structures.opticDisc.centre];

  let weighted = 0;
  for (let r = 0; r < GRID; r++) {
    for (let c = 0; c < GRID; c++) {
      const w = grid[r][c];
      if (w <= 0) continue;
      const p = cellCentre(r, c);
      let nearest = Infinity;
      for (const t of targets) {
        const d = Math.hypot(t.x - p.x, t.y - p.y);
        if (d < nearest) nearest = d;
      }
      weighted += w * Math.exp(-((nearest / SIGMA) ** 2));
    }
  }
  const evidenceOverlapScore = total ? Math.round((weighted / total) * 100) : 0;

  const overlapInterpretation: ExplainabilityResult['overlapInterpretation'] =
    evidenceOverlapScore >= 70 ? 'aligned' : evidenceOverlapScore >= 45 ? 'partial' : 'misaligned';

  /* Top attention regions, described in retinal terms. */
  const cells: AttentionRegion[] = [];
  for (let r = 0; r < GRID; r++) {
    for (let c = 0; c < GRID; c++) {
      if (grid[r][c] <= 0.15) continue;
      const p = cellCentre(r, c);
      const contains = lesions.lesions
        .filter((l) => Math.hypot(l.centre.x - p.x, l.centre.y - p.y) <= 1.2 / GRID)
        .map((l) => LESION_TAXONOMY[l.lesionClass].label);
      cells.push({
        row: r,
        col: c,
        weight: Math.round(grid[r][c] * 100) / 100,
        quadrant: quadrantOf(p, structures.opticDisc.centre, structures.laterality),
        contains: Array.from(new Set(contains)),
      });
    }
  }
  const topRegions = cells.sort((a, b) => b.weight - a.weight).slice(0, 6);

  /* Per-class clinical significance for whatever was actually found. */
  const evidenceNotes = (Object.keys(lesions.counts) as LesionClass[])
    .filter((k) => lesions.counts[k] > 0)
    .sort((a, b) => lesions.counts[b] - lesions.counts[a])
    .map((k) => ({
      lesionClass: k,
      label: LESION_TAXONOMY[k].label,
      count: lesions.counts[k],
      why: LESION_TAXONOMY[k].significance,
    }));

  return {
    gridSize: GRID,
    attentionGrid: grid,
    attentionSource: usingModelAttention ? 'model' : 'image-energy',
    // An image-derived attention field checked against an image-derived lesion
    // list is not an independent check, so it is reported but not used as a
    // safety signal downstream.
    overlapAssessed: usingModelAttention,
    topRegions,
    evidenceOverlapScore,
    overlapInterpretation,
    overlapExplanation: explainOverlap(
      evidenceOverlapScore,
      overlapInterpretation,
      lesionPoints.length,
      usingModelAttention,
    ),
    attentionOnLesionsPct,
    attentionOnAnatomyPct,
    attentionUnexplainedPct,
    evidenceNotes,
    narrative: buildNarrative(
      lesions,
      evidenceOverlapScore,
      overlapInterpretation,
      keyEvidence,
      usingModelAttention,
    ),
  };
}

function cellCentre(r: number, c: number): Point {
  return { x: (c + 0.5) / GRID, y: (r + 0.5) / GRID };
}

function gridFromRegions(regions: GradingReview['attentionRegions']): number[][] {
  const grid = Array.from({ length: GRID }, () => new Array(GRID).fill(0));
  for (const region of regions) {
    const sigma = Math.max(0.04, region.radius);
    for (let r = 0; r < GRID; r++) {
      for (let c = 0; c < GRID; c++) {
        const p = cellCentre(r, c);
        const d = Math.hypot(p.x - region.x, p.y - region.y);
        grid[r][c] += region.weight * Math.exp(-((d / sigma) ** 2));
      }
    }
  }
  return grid;
}

/**
 * Deterministic saliency: local lesion-response energy.
 *
 * Vessel pixels are excluded. Without that the map is simply a picture of the
 * vascular tree — vasculature is by far the strongest departure from a smooth
 * background in any fundus image — which says nothing about where a grading
 * decision came from. What is left is where the retina departs from its own
 * background for reasons other than normal vasculature.
 */
function gridFromImageEnergy(
  img: RasterImage,
  field: RetinalMask,
  vesselMask: Uint8Array,
): number[][] {
  const { width, height, green } = img;
  const background = boxBlur(green, width, height, Math.max(4, Math.round(width * 0.024)));
  const grid = Array.from({ length: GRID }, () => new Array(GRID).fill(0));
  const counts = Array.from({ length: GRID }, () => new Array(GRID).fill(0));

  for (let y = 0; y < height; y++) {
    const r = Math.min(GRID - 1, Math.floor((y / height) * GRID));
    for (let x = 0; x < width; x++) {
      const i = y * width + x;
      if (!field.mask[i] || vesselMask[i]) continue;
      const c = Math.min(GRID - 1, Math.floor((x / width) * GRID));
      const d = background[i] - green[i];
      grid[r][c] += d * d;
      counts[r][c] += 1;
    }
  }
  for (let r = 0; r < GRID; r++) {
    for (let c = 0; c < GRID; c++) {
      grid[r][c] = counts[r][c] > 20 ? grid[r][c] / counts[r][c] : 0;
    }
  }

  return smoothGrid(grid);
}

/** 3x3 mean filter so the energy map forms coherent regions rather than speckle. */
function smoothGrid(grid: number[][]): number[][] {
  const out = Array.from({ length: GRID }, () => new Array(GRID).fill(0));
  for (let r = 0; r < GRID; r++) {
    for (let c = 0; c < GRID; c++) {
      let sum = 0;
      let n = 0;
      for (let dr = -1; dr <= 1; dr++) {
        for (let dc = -1; dc <= 1; dc++) {
          const rr = r + dr;
          const cc = c + dc;
          if (rr < 0 || rr >= GRID || cc < 0 || cc >= GRID) continue;
          sum += grid[rr][cc];
          n++;
        }
      }
      out[r][c] = n ? sum / n : 0;
    }
  }
  return out;
}

function normaliseGrid(grid: number[][]): void {
  let max = 0;
  for (const row of grid) for (const v of row) if (v > max) max = v;
  if (max <= 0) return;
  for (let r = 0; r < grid.length; r++) {
    for (let c = 0; c < grid[r].length; c++) {
      grid[r][c] = Math.round((grid[r][c] / max) * 1000) / 1000;
    }
  }
}

function explainOverlap(
  score: number,
  interpretation: string,
  lesionCount: number,
  modelAttention: boolean,
): string {
  const source = modelAttention
    ? 'The attention field is what the grading model reported as driving its decision.'
    : 'The attention field is the on-device lesion-response energy map, with vasculature suppressed. Because both it and the lesion list are derived from the same image, the score below is reported for information and is NOT used as an independent trust signal — that check requires a model-backed grade.';

  if (lesionCount === 0) {
    return `${source} With no lesions detected, alignment is measured against normal anatomy instead: ${score}/100 of the attention mass sits on the macula and optic disc, which is where a grader looks when confirming a clean retina.`;
  }
  if (interpretation === 'aligned') {
    return `${source} ${score}/100 alignment: the regions that drove the grade sit on top of the lesions that were independently detected. The grade is supported by locatable evidence.`;
  }
  if (interpretation === 'partial') {
    return `${source} ${score}/100 alignment: some of the attention sits on detected lesions, but a meaningful share falls on retina where nothing was found. Treat the grade as supported but not fully evidenced.`;
  }
  return `${source} ${score}/100 alignment: the grade was driven by regions that do not correspond to any independently detected lesion. This is the signature of an unreliable read and forces human review regardless of the confidence score.`;
}

function buildNarrative(
  lesions: LesionAnalysis,
  score: number,
  interpretation: string,
  keyEvidence: string[],
  modelAttention: boolean,
): string {
  const total = Object.values(lesions.counts).reduce((a, b) => a + b, 0);
  const lead =
    total === 0
      ? 'No retinopathy lesions were located, so the grade rests on the absence of findings across a readable field.'
      : `The grade rests on ${total} located finding${total === 1 ? '' : 's'} across the retina.`;
  const evidence = keyEvidence.length
    ? ` Evidence cited by the grading stage: ${keyEvidence.slice(0, 3).join('; ')}.`
    : '';
  const alignment = ` Attention–evidence alignment scores ${score}/100 (${interpretation})${modelAttention ? '' : ', computed from image energy rather than model attention'}.`;
  return lead + evidence + alignment;
}
